name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Expo CLI & EAS CLI
        run: npm install -g expo-cli eas-cli

      - name: Install dependencies
        run: npm install

      - name: Run EAS Build
        env:
          EAS_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production --non-interactive

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KidUply-APK
          path: ./build/**/*.apk
